services:
  macos:
    image: dockurr/macos
    container_name: macos
    environment:
      VERSION: "14"
      ALLOCATE: "Y"
      RAM_SIZE: "half"
      DISK_SIZE: "max"
      CPU_CORES: "max"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 5900:5900/tcp
      - 5900:5900/udp
    volumes:
      - ./macos:/storage
    restart: on-failure
    stop_grace_period: 2m
